title: Rimurus Docs
description: Documentation for Rimurus menu script
post_search: true
remote_theme: pages-themes/architect@v0.2.0
show_downloads: true
github:
  is_project_page: false
  zip_url:https://github.com/Rimmuru/Rimurus-2T1-Scripts/releases/tag/rm-v2.12.0/release.zip
plugins:
- jekyll-remote-theme
